### ISSUE TITLE
Error report after submitting a order

### ISSUE THREAD

**Issue by spiegel** [extcode/cart#103]
Since a view days i get this error when i try to submit a order:

Oops, an error occurred!
Incorrect integer value: '' for column 'tax' at row 1

Before everything worked like a charme.
Any idea?

TYPO3 7.6.10
Cart 2.4.3

MySQL 5.7.17-12-log
PHP 7.1

Regards
Btw. great extension. Thanks!

**Comment by dkd-bergmann** [comment]
I have the same problem.

TYPO3 7.6.15
Cart 2.4.0

MySQL 5.7.18
PHP 7.0.15

**Comment by spiegel** [comment]
Write in your LocalConfiguration.php for example after the line

'sqlDebug' => 0,

this

'setDBinit' => 'SET SESSION sql_mode = \'NO_ENGINE_SUBSTITUTION\';',

It works for me :)

**Comment by dkd-bergmann** [comment]
Thx for the answer.
But this is only a temporarily fix not the solution.
With this line, you override die sql_mode and set only 'NO_ENGINE_SUBSTITUTION'.

What you want is to remove this: 'STRICT_TRANS_TABLES'.
You can check the current sql_mode with following line:
SHOW VARIABLES LIKE 'sql_mode' (mysql console)
In your LocalConfiguration.php set the result without 'STRICT_TRANS_TABLES'.
Then you won't have too many side effects.

You can find a description for this problem here: 
https://www.devside.net/wamp-server/mysql-error-incorrect-integer-value-for-column-name-at-row-1

But this is not the solution, the problem is another one.

**Comment by ideenwerft** [comment]
same problem here, other columns, tested on two different servers, this line doesn't help:
'setDBinit' => 'SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';',
