### ISSUE TITLE
accept terms and conditions throws a error 

### ISSUE THREAD

**Issue by celmedia** [extcode/cart#151]
works plugin.tx_cart.settings.validation.orderItem.fields.acceptTerms.options.is = false
works plugin.tx_cart.settings.validation.orderItem.fields.acceptConditions.options.is = false

not working plugin.tx_cart.settings.validation.orderItem.fields.acceptTerms.validator = false
not working plugin.tx_cart.settings.validation.orderItem.fields.acceptConditions.validator = false

trowes a error : 
error : 
Oops, an error occurred!
Argument 2 passed to Extcode\Cart\Domain\Validator\OrderItemValidator::addPropertyValidator() must implement interface TYPO3\CMS\Extbase\Validation\Validator\ValidatorInterface, null given, called in /home/www/web681/html/lindinger/typo3conf/ext/cart/Classes/Controller/CartController.php on line 938

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Same here:

`(1/1) TypeError
Argument 2 passed to Extcode\Cart\Domain\Validator\OrderItemValidator::addPropertyValidator() must implement interface TYPO3\CMS\Extbase\Validation\Validator\ValidatorInterface, null given, called in /var/www/intranet-ar/public/typo3conf/ext/cart/Classes/Controller/Cart/OrderController.php on line 230`

Doesn't work with:

acceptTermsAndConditions.validator = false
acceptTermsAndConditions.validator = Dummystring
acceptTermsAndConditions.validator >

But works with:

acceptTermsAndConditions >

... only if you DON'T set `acceptTermsAndConditions.options.is = whatever` afterwards of course.

Documentation says

> "Add a checkbox for accepting the terms and conditions. If validator is not Boolean the default template wont render a checkbox."

which is why you expect `acceptTermsAndConditions.validator = false` to work. A documentation update should clarify this.
