### ISSUE TITLE
Feature Request:  Browse detail view

### ISSUE THREAD

**Issue by Hobokens** [extcode/cart#187]
Hi,
it would be very nice to browse through the detail views of the products without the need to go back to list view.

Regards
Hobokens

**Comment by Hobokens** [comment]
With pleasure. 
I have a list view with several products (p1, p2, p3 etc.).  In the detail view of p1, I would like to have a link to the detail view of p2. In the detailed view of p2, I would like to have a link to the detailed view of p1 and a link to the detailed view of p3. 

Georg Ringer's News Extension offers this option, which is very user-friendly.

**Comment by rintisch** [comment]
@Hobokens 
Thanks for the explanation.
I remember this feature from EXT:news. I thinks it's useful there in certain circumstances because news might be chronological so navigating this way makes sense.

Nevertheless I cannot see the same benefit for a shop. I have never seen this pattern in another shop which makes sense to me because I can hardly image a customer navigating that way. 
EXT:cart should in my opinion be limited to best-practice to be good maintainable and slim. With this in mind I cannot see this feature become realized. 
What do you think @extcode ?

**Comment by Hobokens** [comment]
@rintisch thanks for your quick reply.
I can see a lot of use cases.
For example, I use cart for a small wool store. Visitors like to look at several types of wool before making a decision. The type of additional navigation discussed here is the easiest way to do this.

I agree with you that this feature is rare in an online store. But I think that if the feature is there, everyone can decide for themselves whether they want to use it.

**Comment by rintisch** [comment]
The problem is imo that you cannot build a shop which fulfils every demand without getting bloated. Someone has to maintain the code in the end.

You could solve the problem on your own with a small ViewHelper which gets the `uid` of the current product and returns the link to the previous / following product (if existing). By using this ViewHelper in your customized template of the detail view the problem is solved. The advantage with this approach is that you could even introduce a more suitable business logic. Maybe it's not useful to simple return the product with `uid+1` but you might want to have the next product within the same category.

**Comment by extcode** [comment]
As far as I can see the news extension uses a ViewHelper (https://github.com/georgringer/news/blob/main/Classes/ViewHelpers/SimplePrevNextViewHelper.php) to solve this.

I can't imagine for cart (or better for the individual product extensions) to include something like this.

In the case of cart, these ViewHelpers should already be individually customized. Let's take extcode/cart-products as an example. The products can be distributed over different folders in a category. It is not possible for editors to realize the sorting of products via different folders. In the frontend it is not so easy to decide which sys_folders with products should be included in the query and which sys_folders should not be included. What is the sorting criterion for products? A typical criterion such as the publication date of a news item does not exist in the extensions, or is perhaps not as relevant as for news.

I can imagine the scenario if you only have a few products. But as a generic approach for the extension, I think it would be too much effort to always test this and adapt it if necessary.

I would be happy to help with the implementation of such a ViewHelper.

In contrast to News, I also see another major disadvantage. The detailed views are added to the cache.There is a function in the controller that creates a cache entry so that the detail page is removed from the cache when a product is changed.
This probably happens faster in the store context than with older news. If I now change the data of a product, the caches of the detail page on which the product is displayed must also be invalidated, otherwise incorrect data may be displayed here. This could certainly be solved, but the effort to maintain this in the long term is too high for me.

Time resources are scarce and as long as there is no reasonable funding for further development, I would not consider this a core feature of cart.
For one or two small stores it would be a nice-to-have, but the small projects don't sponsor cart.

Feel free to email me or contact me via Slack if you need a customized solution for your project. I would also make it available as a PoC for others in a repository, but not develop it further with cart, unless the further development is then also funded.
