### ISSUE TITLE
Allowed countries not rest

### ISSUE THREAD

**Issue by matin73** [extcode/cart#252]
I have following setup:
plugin.tx_cart {
    settings {
        allowedCountries {
          	at = Österreich
          	de = Deutschland
        }
        defaultCountry = at
    }

But I also get "Schweiz" in checkout, because of default typoscript setup of shop:
        allowedCountries {
            de = Deutschland
            at = Österreich
            ch = Schweiz
        }
        defaultCountry = de

Country ch = Schweiz is not removed from list! So I had to reset it by:
plugin.tx_cart {
    settings {
        **allowedCountries >**
        allowedCountries {
          	at = Österreich
          	de = Deutschland
        }
        defaultCountry = at
    }

**Comment by extcode** [comment]
Das ist das Standardverhalten von TypoScript. Es merged die Konfigurationen zu einem großen Konfigurationsarray.
Du musst, wie in Deiner Lösung schon vorgeschlagen, dem TypoScript Parser sagen, dass er den Teil, den die Cart-Erweiterung mitbringt erst einmal löschen soll. Dann wird Dein TypoScript genommen.
Ich denke nicht, dass es sich hier um einen Fehler handelt.

**Comment by matin73** [comment]
... wäre vielleicht ganz gut, die doku dahingehend anzupassen bzw. zu ergänzen.

**Comment by extcode** [comment]
I'm not sure, because first of all, every integrator should know that. And secondly, this would have to be included in many places in the documentation, because the cart extension comes with many different configurations, which you can adapt to your own needs.
I'll see if I can put such a note in a suitable place during the next documentation round.
