### ISSUE TITLE
Order Finisher check Product Availability

### ISSUE THREAD

**Issue by kveldscholten** [extcode/cart#309]
Hi

If two customers order the same item even though there is only one left, the order goes through anyway.

At the end of the order, is there no check whether the products are still available?

**Comment by varioous** [comment]
+1
We have used cart for an booking system. When finishing order (redirecting to payment) i have to check if the room is still available and have to reserve the room. There I need to check the availability once again.

When checking when adding to cart, there comes more problems, because i have to unblock the reservation when session timeout etc. 

Thanks and bytheway: Great work you did on the cart extension!

Kind regards,
Harald

**Comment by rintisch** [comment]
In between it throws an error

> **#1264 Doctrine\DBAL\Exception\DriverException**
>
>An exception occurred while executing a query: Out of range value for column 'stock' at row 1

This should seriously be fixed. I will try to make a PR.
