### ISSUE TITLE
Enhancement - subscribe to products

### ISSUE THREAD

**Issue by liveman1** [extcode/cart#395]
It would be cool to define different services as products, that can be subscribed for a defined period of time & subscription price.
This should also consider automatic renewal or stop of subscriptions as well as the possibility to cancel a subscription within a defined period of time.
Moreover, it would be great to integrate the capability to subscribe a service & checkout during front end registration process of a user (eg using femanager).

**Comment by extcode** [comment]
As you will have noticed when describing the requirement, this is not done with a small change.
I have started a proof-of-concept in which this issue could be implemented with a separate product extension (cart_subscription).
The cases to be considered here are very diverse and usually an internal API has to be provided here so that possibly different payment provider extensions can automatically perform a corresponding renewal and book the necessary fees e.g. via credit card. Here, too, different sources of error must be intercepted. Starting with credit cards whose validity has expired.
I will not be able to implement such programming without a specific project and funding.

**Comment by liveman1** [comment]
Hi Daniel,

great to know! I will definitely need something like that for my website -
still working on the funding…
It would be cool to have some really basic/robust module to prove the
concept & as starting point fore more comprehensive user stories enabling
following:
- show predefined services with a description, defined duration, price in
Euro & German VAT
- select a service to subscribe to
- show front end user data as billing information
- show a link to general terms & conditions with a confirmation check mark
- select PayPal, Apple Pay or Google Pay for payment
- process payment using selected payment service provider
- update user profile with subscribed to service, start date, end date,
price
- sent invoice with user billing information & subscription information to
user email address.

What effort would it be to realise something like that?

In general this would be a great value add for typo3. There are quite a lot
of similar WordPress add-ons. So the motivation of the typo3 community
should be quite high to get this funded & further enhanced  :)

I am looking forward for your feedback.

Best regards
Steffen


Daniel Gohlke ***@***.***> schrieb am Fr. 1. Juli 2022 um
20:32:

**Comment by rintisch** [comment]
I think due to the big scope and the really different use cases this will not be solved. 

@extcode I would like to close this issue, is that okay?

**Comment by extcode** [comment]
I think we can close it for now. This is a huge task to implement this. I think a generic solution is out of the scope. It can be solved individually for a project but not in general for all.

Presenting a solution will lead to further requirements that I cannot guarantee in my free time. And we're not talking about version upgrades yet.

I can imagine offering a customized solution for a project with a specific payment service provider etc.
