### ISSUE TITLE
Missing/ typo getHandleStock in Model

### ISSUE THREAD

**Issue by huersch** [extcode/cart#40]
Hi Daniel,

in the Product Model is a function called handleStock() (Line 1023) that should be getHandlestock.

Could please change that, otherwise you can not call it via fluid.

Thanks
Fabian

**Comment by extcode** [comment]
Hi Fabian,

this will be fixed in the next minor version (1.7.0). I made some changes in this version to handle the stock in the product or for configurable products also in backend variants. I have to invest some time to load the "add to cart"-form via AJAX, so one can add the single view of the product to the cache and have a correct output of the price and availability of the product and/or variants of the product.

**Comment by extcode** [comment]
Solved with version 2.0.0.
