### ISSUE TITLE
payment method needs return url

### ISSUE THREAD

**Issue by celmedia** [extcode/cart#49]
if i add a paymentmethod in typoscript one setting should be   return_url =

**Comment by extcode** [comment]
What is your intention to have a return_url. You can style the OrderCart,html for your own with the the possibility to have access to the order and invoice number and other data from the order item to show it to the customer.
Don't get me wrong, but I need the information because there are different ways to implement this. Do you want to redirect to an external page? Or to an internal page with or without a special controller action parameter. At the moment I don't see the need for a redirect. Give me a good reason and I will implement this feature.

**Comment by celmedia** [comment]
hey daniel ... i have accessoires in the basket page ... that customer needs to see the accessoires befor paying ... but when hes done with payment he should not see them he should bee routet to a other page where the information comes that the order is placed and have also the opertunity to inform about other products or details . see it here : http://trivanti.cel-media.ch/shop/

**Comment by extcode** [comment]
Solved with version 3.0.0.
