### ISSUE TITLE
add to cart - button

### ISSUE THREAD

**Issue by tyranni** [extcode/cart#51]
Hey Daniel,
thank you for your great extension!
Would you be so kind and give some advice how a simple add-to-cart button could be added to a listed product? Sorry if it's a stupid question ;) 

Thank you and best wishes!

**Comment by tyranni** [comment]
Sorry, Daniel :)
I stood on the line ;)

Thanks again and best wishes!

**Comment by extcode** [comment]
If I understand you, you want to show the add-to-cart button in the normal list view?
This is easy. Please copy the cart/Resources/Private/Templates/Product/List.html-Template to your sitepackage or a propper location and add a configuration for this templatePath to TypoScript. In the copied List.html change the line

<f:render partial="Product/Price" arguments="{product: product, settings: settings}"></f:render>

to

<f:render partial="Product/CartForm" arguments="{product: product, settings: settings}"></f:render>.

You do **not** need the <f:cObject typoscriptObjectPath="lib.cartProduct.showForm" /> like in the Show.html because the List.html is not cached.

For futher questions please try to use the ext-cart channel on slack (https://typo3.slack.com/messages/ext-cart/) or use stack overflow and send me the link to the question.

**Comment by tyranni** [comment]
Thanks Daniel!
That is exactly what I did right now ;) 

Best wishes! :)
