### ISSUE TITLE
Third party table for products still possible?

### ISSUE THREAD

**Issue by deflektor01** [extcode/cart#85]
Hi there, 

I want to switch from wt_cart to cart. My first question:

Is cart still usable with an own product-table? I saw some config options for connecting a table still existing in wt_cart, but can't figure out if they are still used.

Thx in advance

**Comment by extcode** [comment]
Hello, this option is available in Cart too. But I changed the behaviour of Cart handling external tables in version 3.0.0. In this version I removed all the mess up in TypoScript but you need to add a little Signal Slot to load your products from your product table. I created a simple extension [CartSimpleProduct](https://github.com/extcode/cart_simple_product) how to load own product tables. This is much cleaner, especially because Cart brings its own product table which covers most of the cases.
